CLASS=esexamreport

DOCSTRIP=latex
PDFLATEX=pdflatex
MAKEINDEX=makeindex

all: $(CLASS).cls $(CLASS).pdf

clean:
	rm -f $(CLASS).{aux,cls,dvi,glo,gls,idx,ilg,ind,log,pdf,ps}

include ../../../tools/latex-class.mk
