CLASS=esexamreport

DOCSTRIP=latex
PDFLATEX=pdflatex
MAKEINDEX=makeindex

all: $(CLASS).cls $(CLASS).pdf

include ../../../tools/latex-class.mk
include ../../../tools/latex-clean.mk
include ../../../tools/latex-doc.mk
