NAME=gsmemo

DOCSTRIP=xelatex
PDFLATEX=xelatex
MAKEINDEX=makeindex

all: $(NAME).cls $(NAME).pdf

include ../../../tools/latex-class.mk
include ../../../tools/latex-clean.mk
include ../../../tools/latex-doc.mk
