CLASS=gsmemo

DOCSTRIP=xelatex
PDFLATEX=xelatex
MAKEINDEX=makeindex

all: $(CLASS).cls $(CLASS).pdf

clean:
	rm -f $(CLASS).{aux,cls,dvi,glo,gls,idx,ilg,ind,log,pdf,ps}

include ../../../tools/latex-class.mk
